version: "3"
containers:
- name: container
  image: ubuntu
  shell: /bin/bash
  memory: 256
  resources:
    memory: 256
virtualmachines:
- name: test-autorefill
  image: debian-cloud/debian-12
  machine_type: n1-standard-1
